"""Legacy database module -- re-exports from core.database for backward compatibility."""
from lightroom_tagger.core.database import (  # noqa: F401
    batch_update_hashes,
    clear_all,
    delete_image,
    generate_key,
    get_all_images,
    get_image,
    get_image_count,
    get_images_without_hash,
    init_database,
    search_by_color_label,
    search_by_date,
    search_by_instagram_posted,
    search_by_keyword,
    search_by_rating,
    store_image,
    store_images_batch,
    update_image_hash,
    update_instagram_status,
)
