/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list_all_jobs <GET> */
        get: operations["get__api_jobs_"];
        put?: never;
        /** create_new_job <POST> */
        post: operations["post__api_jobs_"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get_job_details <GET> */
        get: operations["get__api_jobs_{job_id}"];
        put?: never;
        post?: never;
        /** cancel_job <DELETE> */
        delete: operations["delete__api_jobs_{job_id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** retry_job <POST> */
        post: operations["post__api_jobs_{job_id}_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list_active_jobs <GET> */
        get: operations["get__api_jobs_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Expose subsystem health so the UI can warn before users enqueue broken jobs.
         * @description Returns library DB resolution info plus the job types that require it. Always 200 — ``library_db.exists == false`` is the signal to render a banner.
         */
        get: operations["get__api_jobs_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/_processor_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diagnose the background job processor — was it started, is it ticking?
         * @description This endpoint was added after an incident where a ``pending`` job sat untouched for minutes and there was no way to tell from the outside whether the processor thread was alive, stuck, or never started.
         *
         *     Response shape -------------- - ``running`` (bool): the module-level flag ``job_processor_running``. - ``started_at`` / ``last_iteration_at`` (float | null): unix timestamps. - ``last_iteration_age_seconds`` (float | null): derived convenience. - ``iterations_total`` (int): cheap proof-of-life counter. - ``current_job_id`` / ``current_job_started_at``: what the processor   is actively working on, if anything. - ``pending_count`` (int): outstanding jobs in the DB; useful alongside   ``current_job_id`` to spot "pending but not being picked up". - ``stale`` (bool): convenience flag — True if ``last_iteration_age_seconds``   exceeds :data:`_PROCESSOR_STALE_AFTER_SECONDS`. Clients can treat it   as the primary signal without reimplementing the threshold. - ``last_error`` (str | null): most recent exception string from the   outer ``try`` in the processor loop.
         */
        get: operations["get__api_jobs__processor_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** JobsListResponse */
        "JobsListResponse.45d9b59": {
            /** Total */
            total: number;
            /** Data */
            data: components["schemas"]["JobsListResponse.45d9b59.Job"][];
            pagination: components["schemas"]["JobsListResponse.45d9b59.PaginationMeta"];
        };
        /**
         * ValidationError
         * @description Model of a validation error response.
         */
        "ValidationError.6a07bef": components["schemas"]["ValidationError.6a07bef.ValidationErrorElement"][];
        /** JobCreateRequest */
        "JobCreateRequest.45d9b59": {
            /** Type */
            type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "Job.45d9b59": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["Job.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** ErrorBody */
        "ErrorBody.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @default null
             */
            code: string | null;
        };
        /** CatalogUnavailableError */
        "CatalogUnavailableError.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @constant
             */
            code: "catalog_unavailable";
            library_db: components["schemas"]["CatalogUnavailableError.45d9b59.LibraryDbInfo"];
        };
        /** DbBusyError */
        "DbBusyError.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @constant
             */
            code: "db_busy";
        };
        /**
         * JobListResponse
         * @description ``GET /api/jobs/active`` response body.
         */
        "JobListResponse.45d9b59": components["schemas"]["JobListResponse.45d9b59.Job"][];
        /** JobsHealth */
        "JobsHealth.45d9b59": {
            library_db: components["schemas"]["JobsHealth.45d9b59.LibraryDbInfo"];
            /** Jobs Requiring Catalog */
            jobs_requiring_catalog: string[];
            /** Catalog Available */
            catalog_available: boolean;
        };
        /** JobsProcessorHealth */
        "JobsProcessorHealth.45d9b59": {
            /** Running */
            running: boolean;
            /**
             * Started At
             * @default null
             */
            started_at: number | null;
            /**
             * Last Iteration At
             * @default null
             */
            last_iteration_at: number | null;
            /**
             * Last Iteration Age Seconds
             * @default null
             */
            last_iteration_age_seconds: number | null;
            /**
             * Iterations Total
             * @default 0
             */
            iterations_total: number;
            /**
             * Current Job Id
             * @default null
             */
            current_job_id: string | null;
            /**
             * Current Job Started At
             * @default null
             */
            current_job_started_at: number | null;
            /**
             * Pending Count
             * @default 0
             */
            pending_count: number;
            /**
             * Running Count
             * @default 0
             */
            running_count: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Stale Threshold Seconds */
            stale_threshold_seconds: number;
            /**
             * Last Error
             * @default null
             */
            last_error: string | null;
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "JobsListResponse.45d9b59.Job": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["JobsListResponse.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** JobLog */
        "JobsListResponse.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** PaginationMeta */
        "JobsListResponse.45d9b59.PaginationMeta": {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Current Page */
            current_page: number;
            /** Total Pages */
            total_pages: number;
            /** Has More */
            has_more: boolean;
        };
        /**
         * ValidationErrorElement
         * @description Model of a validation error response element.
         */
        "ValidationError.6a07bef.ValidationErrorElement": {
            /** Missing field name */
            loc: string[];
            /** Error message */
            msg: string;
            /** Error type */
            type: string;
            /**
             * Error context
             * @default null
             */
            ctx: {
                [key: string]: unknown;
            } | null;
        };
        /** JobLog */
        "Job.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** LibraryDbInfo */
        "CatalogUnavailableError.45d9b59.LibraryDbInfo": {
            /** Path */
            path: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "env" | "config" | "default" | "none";
            /** Exists */
            exists: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "JobListResponse.45d9b59.Job": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["JobListResponse.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** JobLog */
        "JobListResponse.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** LibraryDbInfo */
        "JobsHealth.45d9b59.LibraryDbInfo": {
            /** Path */
            path: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "env" | "config" | "default" | "none";
            /** Exists */
            exists: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get__api_jobs_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    post__api_jobs_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest.45d9b59"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogUnavailableError.45d9b59"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    "get__api_jobs_{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "delete__api_jobs_{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    "post__api_jobs_{job_id}_retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    get__api_jobs_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_jobs_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsHealth.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_jobs__processor_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsProcessorHealth.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
}
