/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list_all_jobs <GET> */
        get: operations["get__api_jobs_"];
        put?: never;
        /** create_new_job <POST> */
        post: operations["post__api_jobs_"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get_job_details <GET> */
        get: operations["get__api_jobs_{job_id}"];
        put?: never;
        post?: never;
        /** cancel_job <DELETE> */
        delete: operations["delete__api_jobs_{job_id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** retry_job <POST> */
        post: operations["post__api_jobs_{job_id}_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list_active_jobs <GET> */
        get: operations["get__api_jobs_active"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Expose subsystem health so the UI can warn before users enqueue broken jobs.
         * @description Returns library DB resolution info plus the job types that require it. Always 200 — ``library_db.exists == false`` is the signal to render a banner.
         */
        get: operations["get__api_jobs_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/_processor_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diagnose the background job processor — was it started, is it ticking?
         * @description This endpoint was added after an incident where a ``pending`` job sat untouched for minutes and there was no way to tell from the outside whether the processor thread was alive, stuck, or never started.
         *
         *     Response shape -------------- - ``running`` (bool): the module-level flag ``job_processor_running``. - ``started_at`` / ``last_iteration_at`` (float | null): unix timestamps. - ``last_iteration_age_seconds`` (float | null): derived convenience. - ``iterations_total`` (int): cheap proof-of-life counter. - ``current_job_id`` / ``current_job_started_at``: what the processor   is actively working on, if anything. - ``pending_count`` (int): outstanding jobs in the DB; useful alongside   ``current_job_id`` to spot "pending but not being picked up". - ``stale`` (bool): convenience flag — True if ``last_iteration_age_seconds``   exceeds :data:`_PROCESSOR_STALE_AFTER_SECONDS`. Clients can treat it   as the primary signal without reimplementing the threshold. - ``last_error`` (str | null): most recent exception string from the   outer ``try`` in the processor loop.
         */
        get: operations["get__api_jobs__processor_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/posting-frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bucket counts of validated posts (see ``get_posting_frequency``). */
        get: operations["get__api_analytics_posting-frequency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/posting-heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day-of-week × hour heatmap for validated posts. */
        get: operations["get__api_analytics_posting-heatmap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/caption-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caption length and hashtag aggregates for validated posts. */
        get: operations["get__api_analytics_caption-stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/unposted-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated catalog images with ``instagram_posted = 0`` (matches catalog filters). */
        get: operations["get__api_analytics_unposted-catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list_providers <GET> */
        get: operations["get__api_providers_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/fallback-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** fallback_order <GET> */
        get: operations["get__api_providers_fallback-order"];
        /** fallback_order <PUT> */
        put: operations["put__api_providers_fallback-order"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** defaults <GET> */
        get: operations["get__api_providers_defaults"];
        /** defaults <PUT> */
        put: operations["put__api_providers_defaults"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/models/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flat list of all models across all providers, for the NL/description task selector.
         * @description Each model entry includes ``tool_calling`` from the provider's ``providers.json`` config (function-calling / tools support).
         *
         *     For providers with no statically configured models (e.g. oMLX), attempts a live /v1/models discovery with a short timeout so the selector still includes them when they are running.
         */
        get: operations["get__api_providers_models_description"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** provider_health <GET> */
        get: operations["get__api_providers_{provider_id}_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** delete_model <DELETE> */
        delete: operations["delete__api_providers_{provider_id}_models_{model_id}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/models/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder models for a provider. */
        put: operations["put__api_providers_{provider_id}_models_order"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** models <GET> */
        get: operations["get__api_providers_{provider_id}_models"];
        put?: never;
        /** models <POST> */
        post: operations["post__api_providers_{provider_id}_models"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List perspectives; optional ``active_only=true`` query. */
        get: operations["get__api_perspectives_"];
        put?: never;
        /** create_perspective_route <POST> */
        post: operations["post__api_perspectives_"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** get_perspective_route <GET> */
        get: operations["get__api_perspectives_{slug}"];
        /** update_perspective_route <PUT> */
        put: operations["put__api_perspectives_{slug}"];
        post?: never;
        /** delete_perspective_route <DELETE> */
        delete: operations["delete__api_perspectives_{slug}"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perspectives/{slug}/reset-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** reset_perspective_default_route <POST> */
        post: operations["post__api_perspectives_{slug}_reset-default"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** PostingFrequencyQuery */
        "PostingFrequencyQuery.21fa20e": {
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
            /**
             * Granularity
             * @default day
             */
            granularity: string;
        };
        /** PostingFrequencyResponse */
        "PostingFrequencyResponse.21fa20e": {
            /** Buckets */
            buckets: components["schemas"]["PostingFrequencyResponse.21fa20e.PostingFrequencyBucket"][];
            meta: components["schemas"]["PostingFrequencyResponse.21fa20e.PostingFrequencyMeta"];
        };
        /** ErrorBody */
        "ErrorBody.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @default null
             */
            code: string | null;
        };
        /**
         * ValidationError
         * @description Model of a validation error response.
         */
        "ValidationError.6a07bef": components["schemas"]["ValidationError.6a07bef.ValidationErrorElement"][];
        /** PostingHeatmapQuery */
        "PostingHeatmapQuery.21fa20e": {
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
        };
        /** PostingHeatmapResponse */
        "PostingHeatmapResponse.21fa20e": {
            /** Cells */
            cells: components["schemas"]["PostingHeatmapResponse.21fa20e.HeatmapCell"][];
            meta: components["schemas"]["PostingHeatmapResponse.21fa20e.PostingHeatmapMeta"];
        };
        /** CaptionStatsQuery */
        "CaptionStatsQuery.21fa20e": {
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
        };
        /** CaptionStatsResponse */
        "CaptionStatsResponse.21fa20e": {
            /** Post Count */
            post_count: number;
            /** With Caption Count */
            with_caption_count: number;
            /** Avg Caption Len */
            avg_caption_len: number;
            /** Median Caption Len */
            median_caption_len: number | null;
            /** Top Hashtags */
            top_hashtags: components["schemas"]["CaptionStatsResponse.21fa20e.TopHashtagRow"][];
            /** Posts With Hashtags */
            posts_with_hashtags: number;
            /** Avg Hashtags Per Post */
            avg_hashtags_per_post: number;
            /** Top Words */
            top_words: components["schemas"]["CaptionStatsResponse.21fa20e.TopWordRow"][];
            meta: components["schemas"]["CaptionStatsResponse.21fa20e.CaptionHashtagMeta"];
        };
        /** UnpostedCatalogQuery */
        "UnpostedCatalogQuery.21fa20e": {
            /**
             * Month
             * @default null
             */
            month: string | null;
            /**
             * Min Rating
             * @default null
             */
            min_rating: number | null;
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
            /**
             * Limit
             * @default 50
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** UnpostedCatalogResponse */
        "UnpostedCatalogResponse.21fa20e": {
            /** Total */
            total: number;
            /** Images */
            images: components["schemas"]["UnpostedCatalogResponse.21fa20e.UnpostedCatalogItem"][];
            pagination: components["schemas"]["UnpostedCatalogResponse.21fa20e.PaginationMeta"];
        };
        /** JobsListResponse */
        "JobsListResponse.45d9b59": {
            /** Total */
            total: number;
            /** Data */
            data: components["schemas"]["JobsListResponse.45d9b59.Job"][];
            pagination: components["schemas"]["JobsListResponse.45d9b59.PaginationMeta"];
        };
        /** JobCreateRequest */
        "JobCreateRequest.45d9b59": {
            /** Type */
            type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "Job.45d9b59": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["Job.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** CatalogUnavailableError */
        "CatalogUnavailableError.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @constant
             */
            code: "catalog_unavailable";
            library_db: components["schemas"]["CatalogUnavailableError.45d9b59.LibraryDbInfo"];
        };
        /** DbBusyError */
        "DbBusyError.45d9b59": {
            /** Error */
            error: string;
            /**
             * Code
             * @constant
             */
            code: "db_busy";
        };
        /**
         * JobListResponse
         * @description ``GET /api/jobs/active`` response body.
         */
        "JobListResponse.45d9b59": components["schemas"]["JobListResponse.45d9b59.Job"][];
        /** JobsHealth */
        "JobsHealth.45d9b59": {
            library_db: components["schemas"]["JobsHealth.45d9b59.LibraryDbInfo"];
            /** Jobs Requiring Catalog */
            jobs_requiring_catalog: string[];
            /** Catalog Available */
            catalog_available: boolean;
        };
        /** JobsProcessorHealth */
        "JobsProcessorHealth.45d9b59": {
            /** Running */
            running: boolean;
            /**
             * Started At
             * @default null
             */
            started_at: number | null;
            /**
             * Last Iteration At
             * @default null
             */
            last_iteration_at: number | null;
            /**
             * Last Iteration Age Seconds
             * @default null
             */
            last_iteration_age_seconds: number | null;
            /**
             * Iterations Total
             * @default 0
             */
            iterations_total: number;
            /**
             * Current Job Id
             * @default null
             */
            current_job_id: string | null;
            /**
             * Current Job Started At
             * @default null
             */
            current_job_started_at: number | null;
            /**
             * Pending Count
             * @default 0
             */
            pending_count: number;
            /**
             * Running Count
             * @default 0
             */
            running_count: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Stale Threshold Seconds */
            stale_threshold_seconds: number;
            /**
             * Last Error
             * @default null
             */
            last_error: string | null;
        };
        /**
         * PerspectiveListResponse
         * @description ``GET /api/perspectives/`` response body.
         */
        "PerspectiveListResponse.15b0cf1": components["schemas"]["PerspectiveListResponse.15b0cf1.PerspectiveSummary"][];
        /** PerspectiveDetail */
        "PerspectiveDetail.15b0cf1": {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Active */
            active: boolean;
            /** Optional */
            optional: boolean;
            /**
             * Source Filename
             * @default null
             */
            source_filename: string | null;
            /**
             * Updated At
             * @default null
             */
            updated_at: string | null;
            /** Prompt Markdown */
            prompt_markdown: string;
            /**
             * Created At
             * @default null
             */
            created_at: string | null;
        };
        /**
         * ProviderListResponse
         * @description ``GET /api/providers/`` response body.
         */
        "ProviderListResponse.3d6af5f": components["schemas"]["ProviderListResponse.3d6af5f.Provider"][];
        /** FallbackOrderResponse */
        "FallbackOrderResponse.3d6af5f": {
            /** Order */
            order: string[];
        };
        /** ProviderDefaults */
        "ProviderDefaults.3d6af5f": {
            vision_comparison: components["schemas"]["ProviderDefaults.3d6af5f.ProviderDefaultsEntry"];
            description: components["schemas"]["ProviderDefaults.3d6af5f.ProviderDefaultsEntry"];
        };
        /** DescriptionModelsResponse */
        "DescriptionModelsResponse.3d6af5f": {
            /** Models */
            models: components["schemas"]["DescriptionModelsResponse.3d6af5f.DescriptionModel"][];
            /**
             * Default Provider
             * @default null
             */
            default_provider: string | null;
            /**
             * Default Model
             * @default null
             */
            default_model: string | null;
        };
        /** ProviderHealthResponse */
        "ProviderHealthResponse.3d6af5f": {
            /** Reachable */
            reachable: boolean;
            /**
             * Error
             * @default null
             */
            error: string | null;
        };
        /** ProviderDeletedResponse */
        "ProviderDeletedResponse.3d6af5f": {
            /** Deleted */
            deleted: boolean;
        };
        /** ProviderReorderSuccessResponse */
        "ProviderReorderSuccessResponse.3d6af5f": {
            /** Success */
            success: boolean;
        };
        /**
         * ProviderModelsListResponse
         * @description ``GET /api/providers/<id>/models`` response body.
         */
        "ProviderModelsListResponse.3d6af5f": components["schemas"]["ProviderModelsListResponse.3d6af5f.ProviderModel"][];
        /** ProviderModel */
        "ProviderModel.3d6af5f": {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "config" | "discovered" | "user";
            /**
             * Vision
             * @default null
             */
            vision: boolean | null;
        };
        /** PostingFrequencyBucket */
        "PostingFrequencyResponse.21fa20e.PostingFrequencyBucket": {
            /** Bucket Start */
            bucket_start: string;
            /** Count */
            count: number;
        };
        /** PostingFrequencyMeta */
        "PostingFrequencyResponse.21fa20e.PostingFrequencyMeta": {
            /**
             * Timestamp Source
             * @default null
             */
            timestamp_source: string | null;
            /**
             * Granularity
             * @default null
             */
            granularity: string | null;
            /**
             * Timezone Assumption
             * @default null
             */
            timezone_assumption: string | null;
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
            /**
             * Bucket Expression
             * @default null
             */
            bucket_expression: string | null;
        };
        /**
         * ValidationErrorElement
         * @description Model of a validation error response element.
         */
        "ValidationError.6a07bef.ValidationErrorElement": {
            /** Missing field name */
            loc: string[];
            /** Error message */
            msg: string;
            /** Error type */
            type: string;
            /**
             * Error context
             * @default null
             */
            ctx: {
                [key: string]: unknown;
            } | null;
        };
        /** HeatmapCell */
        "PostingHeatmapResponse.21fa20e.HeatmapCell": {
            /** Dow */
            dow: number;
            /** Hour */
            hour: number;
            /** Count */
            count: number;
        };
        /** PostingHeatmapMeta */
        "PostingHeatmapResponse.21fa20e.PostingHeatmapMeta": {
            /**
             * Dow Labels
             * @default null
             */
            dow_labels: string[] | null;
            /**
             * Timezone Assumption
             * @default null
             */
            timezone_assumption: string | null;
            /**
             * Timezone Note
             * @default null
             */
            timezone_note: string | null;
            /**
             * Date From
             * @default null
             */
            date_from: string | null;
            /**
             * Date To
             * @default null
             */
            date_to: string | null;
        };
        /** CaptionHashtagMeta */
        "CaptionStatsResponse.21fa20e.CaptionHashtagMeta": {
            /**
             * Timezone Assumption
             * @default null
             */
            timezone_assumption: string | null;
            /**
             * Hashtag Pattern
             * @default null
             */
            hashtag_pattern: string | null;
            /**
             * Timestamp Scope
             * @default null
             */
            timestamp_scope: string | null;
        };
        /** TopHashtagRow */
        "CaptionStatsResponse.21fa20e.TopHashtagRow": {
            /** Tag */
            tag: string;
            /** Count */
            count: number;
        };
        /** TopWordRow */
        "CaptionStatsResponse.21fa20e.TopWordRow": {
            /** Word */
            word: string;
            /** Count */
            count: number;
        };
        /** PaginationMeta */
        "UnpostedCatalogResponse.21fa20e.PaginationMeta": {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Current Page */
            current_page: number;
            /** Total Pages */
            total_pages: number;
            /** Has More */
            has_more: boolean;
        };
        /** UnpostedCatalogItem */
        "UnpostedCatalogResponse.21fa20e.UnpostedCatalogItem": {
            /** Key */
            key: string;
            /** Filename */
            filename: string;
            /** Date Taken */
            date_taken: string;
            /** Rating */
            rating: number;
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "JobsListResponse.45d9b59.Job": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["JobsListResponse.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** JobLog */
        "JobsListResponse.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** PaginationMeta */
        "JobsListResponse.45d9b59.PaginationMeta": {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Current Page */
            current_page: number;
            /** Total Pages */
            total_pages: number;
            /** Has More */
            has_more: boolean;
        };
        /** JobLog */
        "Job.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** LibraryDbInfo */
        "CatalogUnavailableError.45d9b59.LibraryDbInfo": {
            /** Path */
            path: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "env" | "config" | "default" | "none";
            /** Exists */
            exists: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /**
         * Job
         * @description Shared by REST job endpoints and ``job_updated`` / ``job_created`` socket emits.
         */
        "JobListResponse.45d9b59.Job": {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /** Progress */
            progress: number;
            /**
             * Current Step
             * @default null
             */
            current_step: string | null;
            /** Logs */
            logs?: components["schemas"]["JobListResponse.45d9b59.JobLog"][];
            /**
             * Logs Total
             * @default 0
             */
            logs_total: number;
            /**
             * Warning Count
             * @default 0
             */
            warning_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Last Log At
             * @default null
             */
            last_log_at: string | null;
            /**
             * Result
             * @default null
             */
            result: unknown | null;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Error Severity
             * @default null
             */
            error_severity: ("warning" | "error" | "critical") | null;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Completed At
             * @default null
             */
            completed_at: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Cancel Noop
             * @default null
             */
            cancel_noop: boolean | null;
            /**
             * Cancel Noop Reason
             * @default null
             */
            cancel_noop_reason: string | null;
        };
        /** JobLog */
        "JobListResponse.45d9b59.JobLog": {
            /** Timestamp */
            timestamp: string;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** LibraryDbInfo */
        "JobsHealth.45d9b59.LibraryDbInfo": {
            /** Path */
            path: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "env" | "config" | "default" | "none";
            /** Exists */
            exists: boolean;
            /**
             * Reason
             * @default null
             */
            reason: string | null;
        };
        /** PerspectiveSummary */
        "PerspectiveListResponse.15b0cf1.PerspectiveSummary": {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Active */
            active: boolean;
            /** Optional */
            optional: boolean;
            /**
             * Source Filename
             * @default null
             */
            source_filename: string | null;
            /**
             * Updated At
             * @default null
             */
            updated_at: string | null;
        };
        /** Provider */
        "ProviderListResponse.3d6af5f.Provider": {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Tool Calling */
            tool_calling: boolean;
        };
        /** ProviderDefaultsEntry */
        "ProviderDefaults.3d6af5f.ProviderDefaultsEntry": {
            /** Provider */
            provider: string;
            /**
             * Model
             * @default null
             */
            model: string | null;
        };
        /** DescriptionModel */
        "DescriptionModelsResponse.3d6af5f.DescriptionModel": {
            /** Provider Id */
            provider_id: string;
            /** Provider Name */
            provider_name: string;
            /** Model Id */
            model_id: string;
            /** Model Name */
            model_name: string;
            /** Tool Calling */
            tool_calling: boolean;
        };
        /** ProviderModel */
        "ProviderModelsListResponse.3d6af5f.ProviderModel": {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "config" | "discovered" | "user";
            /**
             * Vision
             * @default null
             */
            vision: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get__api_jobs_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    post__api_jobs_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest.45d9b59"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogUnavailableError.45d9b59"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    "get__api_jobs_{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "delete__api_jobs_{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    "post__api_jobs_{job_id}_retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job.45d9b59"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbBusyError.45d9b59"];
                };
            };
        };
    };
    get__api_jobs_active: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_jobs_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsHealth.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_jobs__processor_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsProcessorHealth.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_analytics_posting-frequency": {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                granularity?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingFrequencyResponse.21fa20e"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_analytics_posting-heatmap": {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostingHeatmapResponse.21fa20e"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_analytics_caption-stats": {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptionStatsResponse.21fa20e"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_analytics_unposted-catalog": {
        parameters: {
            query?: {
                month?: string | null;
                min_rating?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnpostedCatalogResponse.21fa20e"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_providers_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse.3d6af5f"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_providers_fallback-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FallbackOrderResponse.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "put__api_providers_fallback-order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FallbackOrderResponse.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_providers_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDefaults.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    put__api_providers_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDefaults.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_providers_models_description: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescriptionModelsResponse.3d6af5f"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_providers_{provider_id}_health": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealthResponse.3d6af5f"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "delete__api_providers_{provider_id}_models_{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDeletedResponse.3d6af5f"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "put__api_providers_{provider_id}_models_order": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderReorderSuccessResponse.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_providers_{provider_id}_models": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModelsListResponse.3d6af5f"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModel.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "post__api_providers_{provider_id}_models": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModelsListResponse.3d6af5f"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModel.3d6af5f"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    get__api_perspectives_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerspectiveListResponse.15b0cf1"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    post__api_perspectives_: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerspectiveDetail.15b0cf1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "get__api_perspectives_{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerspectiveDetail.15b0cf1"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "put__api_perspectives_{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerspectiveDetail.15b0cf1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "delete__api_perspectives_{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
    "post__api_perspectives_{slug}_reset-default": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerspectiveDetail.15b0cf1"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody.45d9b59"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError.6a07bef"];
                };
            };
        };
    };
}
