"""Instagram ↔ catalog matching: candidates, scoring, vision batch path, orchestration."""

from ._legacy import (
    BATCH_MAX_TOKENS_ESCALATION,
    Callable,
    InstagramCache,
    ProviderRegistry,
    _call_batch_chunk,
    _compute_desc_scores_for_candidates,
    _deserialize_row,
    compare_descriptions_batch,
    find_candidates_by_date,
    get_cached_phash,
    get_or_create_cached_image,
    get_vision_comparison,
    get_vision_model,
    match_batch,
    match_image,
    os,
    query_by_exif,
    score_candidates,
    score_candidates_with_vision,
    store_match,
    store_vision_comparison,
    text_similarity,
)

__all__ = [
    "BATCH_MAX_TOKENS_ESCALATION",
    "Callable",
    "InstagramCache",
    "ProviderRegistry",
    "_call_batch_chunk",
    "_compute_desc_scores_for_candidates",
    "_deserialize_row",
    "compare_descriptions_batch",
    "find_candidates_by_date",
    "get_cached_phash",
    "get_or_create_cached_image",
    "get_vision_comparison",
    "get_vision_model",
    "match_batch",
    "match_image",
    "os",
    "query_by_exif",
    "score_candidates",
    "score_candidates_with_vision",
    "store_match",
    "store_vision_comparison",
    "text_similarity",
]
