"""Library database — barrel re-exports from split scaffold (plan 14-01)."""

from lightroom_tagger.core.managed_connections import (
    managed_catalog,
    managed_library_db,
)

from .db_init import (
    _deserialize_row,
    _dict_factory,
    _ensure_sqlite_vec_loaded,
    _migrate_add_column,
    _migrate_catalog_similarity,
    _migrate_image_clip_embeddings_vec0,
    _migrate_image_descriptions_fts,
    _migrate_image_stacks,
    _migrate_images_schema,
    _migrate_unified_image_keys,
    _perspective_seed_description,
    _serialize_json,
    init_database,
    migrate_unified_image_keys,
    seed_perspectives_from_prompts_dir,
)
from .db_init_migrations import _library_db_file_path

from .insights_summary import (
    InsightsSummary,
    PerspectiveCoverageRow,
    get_insights_summary,
)

from .catalog_statistics import (
    CatalogSchemaFacets,
    catalog_schema_facets,
    count_catalog_images_with_descriptions,
    count_catalog_images_with_repetition,
    count_images_with_dominant_colors,
    count_images_with_mood_tags,
    count_rated_catalog_images,
    get_catalog_date_range,
    get_catalog_months,
    get_color_label_statistics,
    get_mood_tags_sample,
    get_posted_images_count,
)

from .catalog import (
    _LIBRARY_WRITE_LOCK,
    _append_query_catalog_image_filters,
    _non_empty_str_list_for_json_array_filter,
    batch_update_hashes,
    catalog_key_is_primary_grid_row,
    clear_all,
    delete_image,
    filter_order_keys_in_catalog,
    generate_key,
    get_all_catalog_images,
    get_all_images,
    get_all_images_raw,
    get_best_current_catalog_score,
    get_catalog_images_missing_cache,
    get_catalog_images_needing_analysis,
    get_image,
    get_image_count,
    get_images_without_hash,
    init_catalog_table,
    library_write,
    query_catalog_images,
    query_catalog_images_by_keys,
    resolve_filepath,
    search_by_color_label,
    search_by_date,
    search_by_instagram_posted,
    search_by_keyword,
    search_by_rating,
    set_instagram_posted,
    store_catalog_image,
    store_image,
    store_images_batch,
    update_image_hash,
    update_instagram_status,
)

from lightroom_tagger.core.exceptions import StackMutationError

from .stacks import (
    catalog_image_stack_row_fields,
    list_catalog_stack_member_keys,
    list_stack_member_keys,
    select_stack_representative_key_for_keys,
    stack_exists,
    stack_merge_into,
    stack_metadata_for_api,
    stack_set_representative,
    stack_split_member_out,
)

from .descriptions import (
    build_description_fts_query,
    build_description_search_document,
    get_all_image_descriptions,
    get_all_images_with_descriptions,
    get_image_description,
    get_image_descriptions_by_type,
    get_undescribed_catalog_images,
    init_image_descriptions_table,
    store_image_description,
    _coerce_has_repetition,
    _visual_attr_json,
)

from .scores import (
    delete_perspective,
    get_all_current_perspective_slugs,
    get_available_score_perspectives_for_image,
    get_current_scores_for_image,
    get_perspective_by_slug,
    insert_image_score,
    insert_perspective,
    list_all_scores_for_image,
    list_perspectives,
    list_score_history_for_perspective,
    markdown_marks_optional,
    supersede_previous_current_scores,
    update_perspective,
)

from .embeddings import (
    list_catalog_keys_for_clip_embed_force,
    list_catalog_keys_needing_clip_embedding,
    upsert_image_clip_embedding,
    _list_catalog_keys_clip_embed_sql_params,
    _sort_catalog_key_rows_newest_first,
)

from .similarity import (
    clear_catalog_similarity_results,
    get_catalog_similarity_groups_paginated,
    get_similarity_candidates_for_group,
    get_similarity_groups_count,
    insert_catalog_similarity_group,
    list_clip_embedded_catalog_keys_newest_first,
)

from .frame_substance import (
    count_frame_substance_by_unknown_reason,
    count_frame_substance_by_verdict,
    finish_frame_substance_run,
    get_frame_substance_verdict,
    get_latest_finished_frame_substance_run,
    has_frame_substance_override,
    insert_frame_substance_override,
    insert_frame_substance_run,
    list_catalog_images_with_vision_cache,
    load_frame_substance_verdict_map,
    upsert_frame_substance_verdict,
    upsert_frame_substance_verdicts,
)

from .stack_suggestions import (
    BLANK_FRAME_SCORE_FLOOR,
    count_pending_stack_suggestions,
    is_blank_frame_catalog_key,
    is_catalog_similarity_pair_rejected,
    list_pending_stack_suggestions,
    normalize_image_pair,
    reject_catalog_similarity_pair,
    stack_accept_suggestion_pair,
    stack_add_member,
    stack_create_from_keys,
)

from .vision_cache import (
    VISION_CACHE_OVERSIZED_SENTINEL,
    get_cache_stats,
    get_vision_cached_image,
    init_vision_cache_table,
    is_vision_cache_valid,
    store_vision_cached_image,
)

__all__ = (
    'CatalogSchemaFacets',
    'StackMutationError',
    'VISION_CACHE_OVERSIZED_SENTINEL',
    '_LIBRARY_WRITE_LOCK',
    '_append_query_catalog_image_filters',
    '_coerce_has_repetition',
    '_deserialize_row',
    '_dict_factory',
    '_ensure_sqlite_vec_loaded',
    '_library_db_file_path',
    '_list_catalog_keys_clip_embed_sql_params',
    '_migrate_add_column',
    '_migrate_catalog_similarity',
    '_migrate_image_clip_embeddings_vec0',
    '_migrate_image_descriptions_fts',
    '_migrate_image_stacks',
    '_migrate_images_schema',
    '_migrate_unified_image_keys',
    '_non_empty_str_list_for_json_array_filter',
    '_perspective_seed_description',
    '_serialize_json',
    '_sort_catalog_key_rows_newest_first',
    '_visual_attr_json',
    'BLANK_FRAME_SCORE_FLOOR',
    'batch_update_hashes',
    'build_description_fts_query',
    'build_description_search_document',
    'catalog_image_stack_row_fields',
    'catalog_key_is_primary_grid_row',
    'catalog_schema_facets',
    'clear_all',
    'clear_catalog_similarity_results',
    'count_catalog_images_with_descriptions',
    'count_catalog_images_with_repetition',
    'count_images_with_dominant_colors',
    'count_images_with_mood_tags',
    'count_pending_stack_suggestions',
    'count_frame_substance_by_unknown_reason',
    'count_frame_substance_by_verdict',
    'count_rated_catalog_images',
    'delete_image',
    'delete_perspective',
    'filter_order_keys_in_catalog',
    'generate_key',
    'get_all_catalog_images',
    'get_all_current_perspective_slugs',
    'get_all_image_descriptions',
    'get_all_images',
    'get_all_images_raw',
    'get_all_images_with_descriptions',
    'get_available_score_perspectives_for_image',
    'get_cache_stats',
    'get_catalog_date_range',
    'get_catalog_images_missing_cache',
    'get_catalog_images_needing_analysis',
    'get_catalog_months',
    'get_catalog_similarity_groups_paginated',
    'get_color_label_statistics',
    'get_current_scores_for_image',
    'get_best_current_catalog_score',
    'finish_frame_substance_run',
    'get_frame_substance_verdict',
    'get_latest_finished_frame_substance_run',
    'get_image',
    'get_image_count',
    'get_image_description',
    'get_image_descriptions_by_type',
    'get_images_without_hash',
    'get_insights_summary',
    'get_mood_tags_sample',
    'get_perspective_by_slug',
    'get_posted_images_count',
    'get_similarity_candidates_for_group',
    'get_similarity_groups_count',
    'get_undescribed_catalog_images',
    'get_vision_cached_image',
    'init_catalog_table',
    'init_database',
    'init_image_descriptions_table',
    'init_vision_cache_table',
    'InsightsSummary',
    'has_frame_substance_override',
    'insert_frame_substance_override',
    'insert_frame_substance_run',
    'insert_image_score',
    'insert_perspective',
    'is_blank_frame_catalog_key',
    'is_catalog_similarity_pair_rejected',
    'is_vision_cache_valid',
    'library_write',
    'list_all_scores_for_image',
    'list_catalog_images_with_vision_cache',
    'list_catalog_keys_for_clip_embed_force',
    'list_catalog_keys_needing_clip_embedding',
    'list_catalog_stack_member_keys',
    'list_stack_member_keys',
    'list_clip_embedded_catalog_keys_newest_first',
    'list_pending_stack_suggestions',
    'list_perspectives',
    'list_score_history_for_perspective',
    'load_frame_substance_verdict_map',
    'managed_catalog',
    'managed_library_db',
    'markdown_marks_optional',
    'migrate_unified_image_keys',
    'PerspectiveCoverageRow',
    'normalize_image_pair',
    'reject_catalog_similarity_pair',
    'query_catalog_images',
    'query_catalog_images_by_keys',
    'resolve_filepath',
    'search_by_color_label',
    'search_by_date',
    'search_by_instagram_posted',
    'search_by_keyword',
    'search_by_rating',
    'seed_perspectives_from_prompts_dir',
    'select_stack_representative_key_for_keys',
    'set_instagram_posted',
    'stack_accept_suggestion_pair',
    'stack_add_member',
    'stack_create_from_keys',
    'stack_merge_into',
    'stack_metadata_for_api',
    'stack_set_representative',
    'stack_split_member_out',
    'store_catalog_image',
    'store_image',
    'store_image_description',
    'store_images_batch',
    'store_vision_cached_image',
    'supersede_previous_current_scores',
    'update_image_hash',
    'update_instagram_status',
    'update_perspective',
    'upsert_frame_substance_verdict',
    'upsert_frame_substance_verdicts',
    'upsert_image_clip_embedding',
)
