"""Authoritative pydantic models for API response shapes (OpenAPI source of truth)."""

from api.schemas.jobs import (
    ErrorBody,
    Job,
    JobCreateRequest,
    JobLog,
    JobsHealth,
    JobsListResponse,
    JobsProcessorHealth,
    JobsRecoveredPayload,
    LibraryDbInfo,
    PaginationMeta,
    build_job_emit_payload,
    compact_job_payload,
    enrich_job_log_stats,
    validate_job_payload,
    validate_jobs_recovered_payload,
)
from api.schemas.perspectives import (
    PerspectiveDetail,
    PerspectiveListResponse,
    PerspectiveScore,
    PerspectiveSummary,
    validate_perspective_detail,
    validate_perspective_summary,
)
from api.schemas.providers import (
    DescriptionModel,
    DescriptionModelsResponse,
    FallbackOrderResponse,
    Provider,
    ProviderDefaults,
    ProviderDefaultsEntry,
    ProviderDeletedResponse,
    ProviderHealthResponse,
    ProviderModel,
    ProviderListResponse,
    ProviderModelsListResponse,
    ProviderReorderSuccessResponse,
)

__all__ = [
    'DescriptionModel',
    'DescriptionModelsResponse',
    'ErrorBody',
    'FallbackOrderResponse',
    'Job',
    'JobCreateRequest',
    'JobLog',
    'JobsHealth',
    'JobsListResponse',
    'JobsProcessorHealth',
    'JobsRecoveredPayload',
    'LibraryDbInfo',
    'PaginationMeta',
    'PerspectiveDetail',
    'PerspectiveListResponse',
    'PerspectiveScore',
    'PerspectiveSummary',
    'Provider',
    'ProviderDefaults',
    'ProviderDefaultsEntry',
    'ProviderDeletedResponse',
    'ProviderHealthResponse',
    'ProviderModel',
    'ProviderListResponse',
    'ProviderModelsListResponse',
    'ProviderReorderSuccessResponse',
    'build_job_emit_payload',
    'compact_job_payload',
    'enrich_job_log_stats',
    'validate_job_payload',
    'validate_jobs_recovered_payload',
    'validate_perspective_detail',
    'validate_perspective_summary',
]
